; Listing generated by Microsoft (R) Optimizing Compiler Version 18.00.40629.0 

	TITLE	C:\Users\Ryan\Desktop\E-Books\AI\Lua Project 2013\Buckland_Chapter7 to 10_Raven\armory\Weapon_Revolver.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMTD
INCLUDELIB OLDNAMES

END
